### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by PolarPeak** [lzzbb/Adinfo#1]
LDAP Result Code 49 "Invalid Credentials": 80090308: LdapErr: DSID-0C09044E, comment: AcceptSecurityContext error, data 52e, v2580

**Comment by lzzbb** [comment]
Maybe your password is incorrect

**Comment by PolarPeak** [comment]
密码应该没问题，我直接用ladp是可以连接的

**Comment by lzzbb** [comment]
google上有相关的原因，你可以对照着看一下是什么问题
